In [1]:
import numpy as np

In [46]:
nums = np.array([ float(i) / 100 for i in range(1, 25)])
nums = nums.reshape(4, 6)
vals = 1 - nums
print vals

[[ 0.99  0.98  0.97  0.96  0.95  0.94]
 [ 0.93  0.92  0.91  0.9   0.89  0.88]
 [ 0.87  0.86  0.85  0.84  0.83  0.82]
 [ 0.81  0.8   0.79  0.78  0.77  0.76]]


In [32]:
vals1 = np.prod(vals, axis = 0)

In [35]:
print 1 - vals1

[ 0.35118271  0.3796992   0.40726695  0.4339072   0.45964095  0.48448896]


In [31]:
ps = []
for j in range(6):
    p = 1
    for i in range(4):
        p *= vals[i, j]
    ps += p,

In [34]:
print ps == vals1

[ True  True  True  True  True  True]


In [41]:
vals= np.array([ 0.93251787,  0.99984275,  0.99571177,  0.89055819,  0.99998916,  1])

In [45]:
np.exp(vals * 100) / np.exp(100)

array([  1.17297385e-03,   9.84397992e-01,   6.51275195e-01,
         1.76604832e-05,   9.98916587e-01,   1.00000000e+00])

In [47]:
nums = np.array([ float(i) / 100 for i in range(1, 25)])
nums = nums.reshape(4, 6)

In [48]:
print nums

[[ 0.01  0.02  0.03  0.04  0.05  0.06]
 [ 0.07  0.08  0.09  0.1   0.11  0.12]
 [ 0.13  0.14  0.15  0.16  0.17  0.18]
 [ 0.19  0.2   0.21  0.22  0.23  0.24]]


In [51]:
print np.mean(nums, axis = 1)

[ 0.035  0.095  0.155  0.215]
